### ISSUE TITLE
[0.7.0rc] RNOverlayManager is returning nil for it's methodQueue, which is not permitted. (...)

### ISSUE THREAD

**Issue by dvcrn** [brentvatne/react-native-overlay#10]
Hello,

I am trying to run my project and experience the following problem

```
RNOverlayManager is returning nil for it's methodQueue, which is not permitted. You must either return a pre-initialized queue, or @synthesize the methodQueue to let the bridge create a queue for you.
```

I am not sure whether this is a react problem or one with RNOverlay though. 

Related issue - https://github.com/facebook/react-native/issues/1808

**Comment by brentvatne** [comment]
Thanks, this is an issue with the packager right now, it should be resolved soon!

**Comment by ghost** [comment]
hi @brentvatne I am just wondering if this has been resolved yet.  I just upgraded to react-native 0.7.1 and I am still seeing this issue! Thanks

**Comment by brentvatne** [comment]
Hey @potsypantsy - I fixed this and pushed 0.2.8 :smile:

**Comment by ghost** [comment]
@brentvatne thanks! I don't see that error message anymore!

**Comment by sandeepk502119** [comment]
hello @brentvatne 
Today,I try to integrate facebook functionality in my react native app by using component (react-native-facebook-login).In this i Face following error:
RCTFBLoginManager is returning nil for it's methodQueue, which is not permitted. You must either return a pre-initialized queue, or @synthesize the methodQueue to let the bridge create a queue for you.

**Comment by sandeepk502119** [comment]
But Then,I reload the project then it show facebook button in my view alright and work properly.

**Comment by grabbou** [comment]
@sandeepk502119 i reported that issue and they already fixed it

**Comment by grabbou** [comment]
Unfortunately, even though I am using react-native-modal and having correct version of this package, still getting that error.
