### ISSUE TITLE
overlayed component in parent component

### ISSUE THREAD

**Issue by agentS** [brentvatne/react-native-overlay#13]
I'm trying to create an (open-source) slider button which has an animated text layed over a slider. However, when trying to overlay the `Text` component over the slider the `Text` is put on top of the screen into the status bar, as illustrated by the following screenshot (the green arrow indicates where i want the label to be).

![overlay](https://cloud.githubusercontent.com/assets/5032736/8951961/082793ac-35d3-11e5-8a2b-d3db33613107.jpg)

Thus I suppose that the component is put on top of the view. That's why I want to know if there is any possibility of keeping the component wrapped by the `Overlay` in it's parent view instead of putting it on top of the view. As expected, the property `aboveStatusBar={false}` has not solved this issue.

Below you can see my JSX.

```
<View style={styles.container}>
    <Overlay isVisible={true} aboveStatusBar={false}>
        <Animated.Text
            style={[styles.text, styles.textAlignment,
            {
                opacity: this.state.textAlphaValue 
            }
        ]}>
            {this.props.text}
        </Animated.Text>
    </Overlay>

    <SliderIOS key={this.state.timestamp}
        style={[styles.slider, styles.sliderBorder]}
        onSlidingComplete={(newValue) => this.onSliderValueChanged(newValue)}
        {...this.props}>
    </SliderIOS>
</View>
```

**Comment by brentvatne** [comment]
@agentS - sorry for the delay in getting back to you, did you manage to solve this? Unfortunately there is no way to keep it in the parent view, but you might be able to work around it in some other way, let me know if you come up with something!

**Comment by agentS** [comment]
Thanks for your reply. I'm currently on a (forced) holiday and hope to fix it next week.

**Comment by agentS** [comment]
Having used a pure `react-native` solution I have been able to solve this issue. The solution can be found  in the source code of my module [react-native-slider-button](https://github.com/agentS/react-native-slider-button)
