### ISSUE TITLE
Does this project have the equivalent of a bringToFront?

### ISSUE THREAD

**Issue by pickhardt** [brentvatne/react-native-overlay#15]
Since React Native doesn't support zIndex, I'm looking for a way to bring an element to the front of the rendering. Looks like this project sorta might have the ability to do that, but I don't see something that makes that clear.

Does this codebase have the ability to bring a view to the front of the rendering?

**Comment by pickhardt** [comment]
And if so, you might want to expose it and add it to the readme, or even make a new project out of it.

**Comment by niftylettuce** [comment]
@pickhardt Yes this brings it to the front of the view, on top of everything.
