### ISSUE TITLE
'Cannot Find Protocol'

### ISSUE THREAD

**Issue by johnnyjanzen** [brentvatne/react-native-overlay#18]
Hey Brent - been trying to implement the overlay, but I seem to be getting some errors linking it into my project.  I've run through steps 1-4 as outlined in the documentation.

![screen shot 2015-08-24 at 12 46 45 pm](https://cloud.githubusercontent.com/assets/9919877/9450585/57b01c56-4a5e-11e5-8931-a22ed6a28f7e.jpg)

Any advice would be greatly appreciated.  Peace, and appreciate all the work you do.

**Comment by albertwchang** [comment]
Have exactly the same issue
![screen shot 2015-08-29 at 11 11 43 pm](https://cloud.githubusercontent.com/assets/3760499/9566017/5ecc53c8-4ea6-11e5-9f8c-94d8690a278a.png)

**Comment by grabbou** [comment]
This is already fixed I believe, @brentvatne
