### ISSUE TITLE
Overlay brings View to the top, but the viewPosition changes to top-left (absolute?)

### ISSUE THREAD

**Issue by ms88privat** [brentvatne/react-native-overlay#20]
I have a nested component within an ImageView for correct alignment. But then I wanted to animate it outside the image (and above the other components). 

So i wrapped the component within an Overlay. 

But now the starting position is completely wrong (top-left). Is this the intended behaviour? Because if i have to adjust the position absolute anyways, i could simple put the view on the bottom of my renderView without the need of the Overlay component?

greetings

**Comment by niftylettuce** [comment]
This might be related to #21, I had the same issue, and I had to add width to not get it to be stuck at top left.  I just used `Dimensions` and `Dimensions.get('window').width` and `height` to make it fill the screen.

**Comment by niftylettuce** [comment]
@ms88privat do you still have this issue or was it resolved?

**Comment by ms88privat** [comment]
@niftylettuce I ended up not using it. We can close this for now.
