### ISSUE TITLE
requireNativeComponent is not a function

### ISSUE THREAD

**Issue by pbattisson** [brentvatne/react-native-overlay#28]
Hi I am getting the following error

<img width="458" alt="screen shot 2015-11-06 at 16 14 51" src="https://cloud.githubusercontent.com/assets/795556/11001869/8bdde88c-84a1-11e5-9bce-ca5c8abc4800.png">

It seems to be that the "requireNativeComponent" call is not working. I am using ReactNative 0.11.0 and iOS 9. Any ideas on howto resolve this?

**Comment by joeferraro** [comment]
@pbattisson replacing 

```
var React = require('react-native');
var {
  View,
  PropTypes,
  StyleSheet,
  requireNativeComponent,
} = React;
```

with 

```
var React = require('react-native');
var {
  View,
  PropTypes,
  StyleSheet
} = React;

var requireNativeComponent = require('requireNativeComponent');
```

in Overlay.ios.js resolves this issue.

**Comment by pbattisson** [comment]
That has worked, thanks @joeferraro

**Comment by hamza-ain-uddin-khan** [comment]
Uncaught TypeError: (0 , _reactNative.requireNativeComponent) is not a function
/node_modules/react-native-pager-view/lib/module/PagerViewNative.js
tried above solution but no luck
