### ISSUE TITLE
Height does not get updated with aboveStatusBar={true}

### ISSUE THREAD

**Issue by mbrgm** [brentvatne/react-native-overlay#3]
For some reason the overlay is exactly 64px too small. If I manually set `bottom: -64px` in Overlay.ios.js, the overlay fills the screen, but otherwise it is not large enough. I checked the height of the UIView and it seemed to be correct -- so I suppose the error is somewhere in the JS. Maybe the view gets laid out before the UIView has the full height?

**Comment by mbrgm** [comment]
I did some experiments and the overlay works when placed in a component with full screen height, but not otherwise:

```
+-----------------------------------------------+
|                                               |
|-----------------------------------------------|
|                                               |
|-----------------------------------------------|
|             owning component                  |
+-----------------------------------------------+
```
- `aboveStatusBar = true` and `isVisible = true` from the start, it will remain below the other two components
- `aboveStatusBar = true` and `isVisible` becomes true at a later point in time, it will be placed at the top of the screen, but its height will stay as if it was placed within its owning component (`aboveStatusBar = false`)

Hope this helps!

**Comment by niftylettuce** [comment]
Possibly related to #4, did you fix? @mbrgm

**Comment by mbrgm** [comment]
I switched from RN to native development for several other reasons, so I won't be able to check, sorry :-/.

**Comment by niftylettuce** [comment]
See #36 - we will be refactoring this soon to support Android/iOS and not have any issues here, there will no longer be the XCode integration needed

**Comment by mbrgm** [comment]
I'll close this as it is not an issue for me anymore and I won't be able to check whether it's resolved anyway. Feel free to reopen if you disagree. :)
