### ISSUE TITLE
Library for Android?

### ISSUE THREAD

**Issue by LongPotato** [brentvatne/react-native-overlay#42]
I have a warning when running on Android. It could not find the RNOverlay library file.
I think this is the reason why panResponder doesn't work with the components I nested in Overlay on Android.

Can you give me some info about this? Thanks

**Comment by brentvatne** [comment]
No support for Android currently, I would accept a PR that just uses [Portal](https://github.com/facebook/react-native/blob/master/Libraries/Portal/Portal.js) on Android :)

**Comment by waleedarshad-vf** [comment]
+1
