### ISSUE TITLE
using peerDependencies over dependencies.

### ISSUE THREAD

**Issue by alinz** [brentvatne/react-native-overlay#7]
Do you think using `peerDependencies` over `dependencies` in `package.json` would be a good idea?

**Comment by brentvatne** [comment]
Hey there! I think maybe I'm confused about the question - I'm using `peerDependencies` currently: https://github.com/brentvatne/react-native-overlay/blob/master/package.json#L18-L20

**Comment by alinz** [comment]
My bad. :( so embarrassed. Sorry!

**Comment by brentvatne** [comment]
haha no problem :smile:
